version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kcc}
      POSTGRES_USER: ${POSTGRES_USER:-kcc}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kcc}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./apps/api
    restart: unless-stopped
    env_file:
      - ./apps/api/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kcc}
      POSTGRES_USER: ${POSTGRES_USER:-kcc}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kcc}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - ./apps/api:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >-
      bash -c "python manage.py migrate && gunicorn kcc.wsgi:application --bind 0.0.0.0:8000"

volumes:
  db_data:
