version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kcc}
      POSTGRES_USER: ${POSTGRES_USER:-kcc}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kcc}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./apps/api
    restart: unless-stopped
    env_file:
      - ./apps/api/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kcc}
      POSTGRES_USER: ${POSTGRES_USER:-kcc}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kcc}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - ./apps/api:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >-
      bash -c "python manage.py migrate && gunicorn kcc.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - kitchen-network

  # React Frontend
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - kitchen-network

  # Streamlit App (for admin/management)
  streamlit:
    build: .
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run Dashboard.py --server.port=8501 --server.address=0.0.0.0
    networks:
      - kitchen-network

volumes:
  db_data:

networks:
  kitchen-network:
    driver: bridge
