[build]
  base = "apps/web"
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
